### ISSUE TITLE
Printing a non-existent file gives a weird error

### ISSUE THREAD

**Issue by grosser** [sparkleformation/sparkle_formation#116] opened 2015-12-17 21:35 UTC
@chrisroberts not urgent, just annoying / confusing

```
sfn print -f does_not_exist.rb
ERROR: NoMethodError: undefined method `push' for nil:NilClass
```

**Comment by chrisroberts** [comment] 2015-12-17 21:56
I cannot reproduce this error. Perhaps it's a configuration issue or bad content. `DEBUG=true` will provide the stacktrace and will be helpful to determine the origin and provide a useful error message.

```
→ sfn print -f does_not_exist.rb
ERROR: SparkleFormation::Error::NotFound::Template: ["No template registered with requested name (does_not_exist.rb)!"]
```

**Comment by grosser** [comment] 2015-12-17 23:25
looks like it needs at least 1 component, see https://github.com/grosser/sparkle-load/tree/test

**Comment by luckymike** [comment] 2015-12-18 07:51
I just checked out the repo and attempted to reproduce:
```
~/Development/sparkle-load (master) $ sfn print -f not-here.rb
TESTING
ERROR: SparkleFormation::Error::NotFound::Template: ["No template registered with requested name (not-here.rb)!"]
```
And running the exact example: 
```
~/Development/sparkle-load (master) $ sfn print -f does_not_exist.rb
TESTING
ERROR: SparkleFormation::Error::NotFound::Template: ["No template registered with requested name (does_not_exist.rb)!"]
```

**Comment by chrisroberts** [comment] 2015-12-18 14:02
It is reproducible on the `test` branch. I'll leave this issue open so that I include an init guard within the pack. However, the contents of the repository are not structured or implemented in a manner defined within the documentation and as such the behavior around this usage is and should be considered undefined.

**Comment by luckymike** [comment] 2015-12-18 17:05
My bad, I missed the branch when cloning.

**Comment by chrisroberts** [comment] 2016-03-29 13:22
This was fixed by #123

**Closed by chrisroberts** 2016-03-29 13:22 UTC
Labels: enhancement

**Comment by grosser** [comment] 2016-03-29 15:36
:heart: thx for following up on that :D
