### ISSUE TITLE
Parameters for SparkleFormation.compile method

### ISSUE THREAD

**Issue by yhuang** [sparkleformation/sparkle_formation#36] opened 2015-01-19 07:02 UTC
I see how a given CloudFormation template is generated:

puts JSON.pretty_generate(
  SparkleFormation.compile('ec2_example.rb')
)

What I would love is for the compile method to take parameters such that the resulting template would have the corresponding resources defined based on the user-supplied parameters.  In my particular use case, I am defining RDS master and read replicas all in one template.  I would like to change the number of read replicas via CloudFormation stack update operations based on our production traffic.  I have this use case working with cfn-pyplates; however, since I am more comfortable in Ruby, I would love to be able to do the same with SparkleFormation.  Is this capability currently available?  If so, please help me figure out how to code it.  Thank you so much for your help.

**Comment by chrisroberts** [comment] 2015-01-19 14:19
Hi! This feature exists "under the hood" in the library but is not directly exposed. I have found in the past using local variables to generate dynamic numbers of resources, defining constant values and such can some times be the "easy" way out when a "proper" solution already exists within CFN. Because of this I haven't made any real integrations for providing user input into the template generation itself (though it is possible to side step using things like ENV).

Using the read replicas for RDS is a great example of where this isn't the case, since each resource must be declared explicitly, and in your case currently, you would need to modify the sparkle formation template each time you wanted to change that number (or use an environment variable which I don't feel is an acceptable solution).

I'll apply some changes to pull the feature out to the `SparkleFormation.compile` method, and integrate the changes into the CLI application to ensure the "real life" behavior is as expected. 

Todo:
* Add alias to provide `#state!`
* Allow setting state via class compile (which filters to instance)
* Create parameter list for template (should be able to setup much like dynamic meta info)

**Comment by chrisroberts** [comment] 2015-01-22 19:46
This latest change will now allow for setting state into the formation structure:

```ruby
SparkleFormation.compile('/path/to/file.rb', :state => {:replica_count => 3})
```
which would allow behavior in the template like:
```ruby
...
  resources do
    state!(:replica_count).times do |i|
      set!("rds_replica_#{i}".to_sym) do
        type 'AWS::RDS::DBInstance'
        properties do
          ...
        end
      end
    end
  end
...
```

**Comment by rabidscorpio** [comment] 2015-08-04 03:37
@chrisroberts, this is great is because as you mention above, there are times when you need to be able to adjust a template programatically.

I'm running into a problem using this "state!" parameter, though, it's not actually getting passed to the template. I keep getting "nil" as the hash that I'm trying to pass in:
```
SparkleFormation.compile(template(pathname), :state => {:yaml_path => pathname})
```
And on the template side, I'm referencing it like this:
```
state!(:yaml_path)
```
Any idea why I'm running into this problem?

**Comment by chrisroberts** [comment] 2015-08-04 16:43
Are you currently running off `develop` branch or `master`?

**Comment by rabidscorpio** [comment] 2015-08-04 16:45
Master

**Comment by rabidscorpio** [comment] 2015-08-06 02:10
@chrisroberts So I've tried both ```develop``` and ```master``` now to no avail.  Is there a specific way to use "state!" that's not clear from the source code or your example? Thanks

**Comment by chrisroberts** [comment] 2015-08-06 15:10
Hi! Sorry for the delay in response. Testing this on my in progress branch worked as expected, yet failed on both `master` and `develop` so I was attempting to track down _why_. The state bits are _mostly_ working in both `master` and `develop` currently, but it is dependent on where you use it. The place where it currently _is not_ working is when you provide a block when instantiating the `SparkleFormation` instance. For example:

* not working:

```ruby
SparkleFormation.new('fubar') do
  testing state!(:my_test_var)
end
```

* working:

```ruby
SparkleFormation.new('fubar').overrides do
  testing state!(:my_test_var)
end
```

Now, this looks to be a timing issue and adding in some debugging output confirmed that as in the first example, the contents of the state was empty, but in the second example, it was set as expected. Digging into the code we find that when a block is provided when we instantiate, it gets loaded:

https://github.com/sparkleformation/sparkle_formation/blob/master/lib/sparkle_formation/sparkle_formation.rb#L348-L350

and looking at the loading:

https://github.com/sparkleformation/sparkle_formation/blob/master/lib/sparkle_formation/sparkle_formation.rb#L379-L383

we see that it is performing the `build` of that block immediately. Comparing to my current working branch, we can see the reason I did not see this behavior:

https://github.com/sparkleformation/sparkle_formation/blob/enhancement/turtles/lib/sparkle_formation/sparkle_formation.rb#L413-L417

because it has been updated to properly cache the block until it is time to compile rather than doing it immediately.

So, that's the long explanation of the issue. I'm currently pushing to get the next major release out as it has a large number of new features and updates. I will see if I can easily get the fix for this backported and released as a patch level bump, but it may take a few days.

Cheers!

**Comment by rabidscorpio** [comment] 2015-08-06 16:11
Awesome, thank you for following up on this, @chrisroberts.  Looking forward to the next major release!

**Comment by rabidscorpio** [comment] 2015-08-14 01:57
@chrisroberts, I noticed you put out a new release but it only has the "map!" and "or!" helpers.  Any chance on a release with the changes you mentioned above?

**Comment by chrisroberts** [comment] 2015-08-31 19:40
@rabidscorpio once i get this next release out i'll get it backported as i'll be keeping a running < 1.0 version for awhile.

**Comment by chrisroberts** [comment] 2015-09-30 14:12
Bumping this to remind myself to backport this in.

**Comment by chrisroberts** [comment] 2015-10-15 23:43
@rabidscorpio sorry for the delay but should be finally getting this backport rolled out tomorrow

**Comment by chrisroberts** [comment] 2015-10-19 23:00
Parameter usage is fully fixed in the 0.x line as of 0.4.0

**Closed by chrisroberts** 2015-10-19 23:00 UTC
Labels: enhancement
